---
openapi: 3.1.0
servers:
  - url: "http://localhost:7071"
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/order":
    post:
      summary: Create Order with list of foods provided
      operationId: create_order_order_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/OrderRequest"
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    FoodItem:
      properties:
        name:
          type: string
          title: Food Name
        quantity:
          type: integer
          title: Food Quantity
      type: object
      required:
        - name
        - quantity
      title: FoodItem
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OrderRequest:
      properties:
        foods:
          items:
            "$ref": "#/components/schemas/FoodItem"
          type: array
          title: List of Foods to order
      type: object
      required:
        - foods
      title: OrderRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
